name: codecov

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: codecov
        uses: codecov/codecov-action@v1
