name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-20.04]
        deno: ["v1.x"]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run
        run: cd test && deno run main.ts
